### ISSUE TITLE
Mini M8S II

### ISSUE THREAD

**Issue by redger-au** [scropion86/Amlogic-S905-S905X#2]
> - **Device Manufacturer :** ?? Beelink ??
> - **Model :** Mini M8S II
> - **SOC :**  S905X  Revision 02a
> - **RAM :** 2 GB
> - **NAND :** 8 GB
> - **Ethenet ship :** Built-in SOC
> - **WiFI Ship :** Ampak AP6212 module

**Comment by scropion86** [comment]
Davies Added thanks @redger-au
